# Generated by Django 2.2.15 on 2022-09-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0002_auto_20220910_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineas_de_credito',
            name='nombre_linea',
        ),
    ]
